pipeline:
  name: internet-banking core-banking-service
  identifier: internetbanking
  projectIdentifier: BY_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: YashwanthTek
        repoName: internet-banking-concept-microservices
        build: <+input>
  stages:
    - stage:
        name: Build and Security Scan
        identifier: Build_Security_Push
        description: Gradle build -> Semgrep SAST -> OWASP -> Docker push
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: hrnslcl
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Gradle Build
                  identifier: gradle_build
                  spec:
                    connectorRef: HarnessDocker
                    image: eclipse-temurin:21.0.2_13-jdk-alpine
                    shell: Sh
                    command: |-
                      set -e
                      cd core-banking-service
                      chmod +x gradlew
                      ./gradlew clean build -x test
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1000m
              - parallel:
                  - step:
                      type: Semgrep
                      name: Semgrep_1
                      identifier: Semgrep_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                          fail_on_severity: high
                        resources:
                          limits:
                            memory: 1Gi
                            cpu: 500m
                  - step:
                      type: Owasp
                      name: Owasp Dependency-Check Scan
                      identifier: Owasp_DependencyCheck_Scan
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                          fail_on_severity: high
                          args:
                            cli: "--disableOssIndex"
                        resources:
                          limits:
                            memory: 4Gi
                            cpu: 2000m
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Docker Image
                  identifier: docker_build_push
                  spec:
                    connectorRef: HarnessDocker
                    repo: yashwanth536/core-banking-service
                    tags:
                      - <+codebase.branch>
                      - <+codebase.commitSha>
                      - <+pipeline.sequenceId>
                    caching: true
                    dockerfile: core-banking-service/Dockerfile
                    context: .
    - stage:
        name: Blue-Green Deployment
        identifier: BlueGreen_Deployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: testqa1
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: bankingdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: bankingdev
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    skipUnchangedManifest: false
              - parallel:
                  - step:
                      name: User Journey Tests
                      identifier: user_journey_tests
                      type: Container
                      timeout: 10m
                      spec:
                        connectorRef: HarnessDocker
                        image: mcr.microsoft.com/playwright:v1.44.0-jammy
                        shell: Sh
                        command: |-
                          apt-get install -y git > /dev/null 2>&1 || true
                          git clone --depth=1 https://github.com/Yashwanth-Tek/internet-banking-concept-microservices.git /app
                          cd /app/tests
                          npm install
                          npx playwright install chromium
                          mkdir -p test-results
                          PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-results/user-journey.xml npx playwright test --config=playwright.config.ts --project=user-journey --reporter=junit
                        envVariables:
                          BASE_URL: http://core-banking-service-svc-stage.banking-dev.svc.cluster.local
                          CI: "true"
                        resources:
                          limits:
                            memory: 1Gi
                            cpu: 500m
                        infrastructure:
                          type: KubernetesDirect
                          spec:
                            connectorRef: hrnslcl
                            namespace: harness-delegate-ng
                            resources:
                              limits:
                                cpu: "1"
                                memory: 1Gi
                            annotations: {}
                            labels: {}
                            containerSecurityContext:
                              capabilities:
                                drop: []
                                add: []
                            nodeSelector: {}
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - /app/tests/test-results/user-journey.xml
                        outputVariables: []
                  - step:
                      name: Regression Tests
                      identifier: regression_tests
                      type: Container
                      timeout: 10m
                      spec:
                        connectorRef: HarnessDocker
                        image: mcr.microsoft.com/playwright:v1.44.0-jammy
                        shell: Sh
                        command: |-
                          apt-get install -y git > /dev/null 2>&1 || true
                          git clone --depth=1 https://github.com/Yashwanth-Tek/internet-banking-concept-microservices.git /app
                          cd /app/tests
                          npm install
                          npx playwright install chromium
                          mkdir -p test-results
                          PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-results/regression.xml npx playwright test --config=playwright.config.ts --project=regression --reporter=junit
                        envVariables:
                          BASE_URL: http://core-banking-service-svc-stage.banking-dev.svc.cluster.local
                          CI: "true"
                        resources:
                          limits:
                            memory: 1Gi
                            cpu: 500m
                        infrastructure:
                          type: KubernetesDirect
                          spec:
                            connectorRef: hrnslcl
                            namespace: harness-delegate-ng
                            resources:
                              limits:
                                cpu: "1"
                                memory: 1Gi
                            annotations: {}
                            labels: {}
                            containerSecurityContext:
                              capabilities:
                                drop: []
                                add: []
                            nodeSelector: {}
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - /app/tests/test-results/regression.xml
                        outputVariables: []
                  - step:
                      name: Integration Tests
                      identifier: integration_tests
                      type: Container
                      timeout: 10m
                      spec:
                        connectorRef: HarnessDocker
                        image: mcr.microsoft.com/playwright:v1.44.0-jammy
                        shell: Sh
                        command: |-
                          apt-get install -y git > /dev/null 2>&1 || true
                          git clone --depth=1 https://github.com/Yashwanth-Tek/internet-banking-concept-microservices.git /app
                          cd /app/tests
                          npm install
                          npx playwright install chromium
                          mkdir -p test-results
                          PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-results/integration.xml npx playwright test --config=playwright.config.ts --project=integration --reporter=junit
                        envVariables:
                          BASE_URL: http://core-banking-service-svc-stage.banking-dev.svc.cluster.local
                          CI: "true"
                        resources:
                          limits:
                            memory: 1Gi
                            cpu: 500m
                        infrastructure:
                          type: KubernetesDirect
                          spec:
                            connectorRef: hrnslcl
                            namespace: harness-delegate-ng
                            resources:
                              limits:
                                cpu: "1"
                                memory: 1Gi
                            annotations: {}
                            labels: {}
                            containerSecurityContext:
                              capabilities:
                                drop: []
                                add: []
                            nodeSelector: {}
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - /app/tests/test-results/integration.xml
                        outputVariables: []
                  - step:
                      name: API Contract Tests
                      identifier: api_contract_tests
                      type: Container
                      timeout: 10m
                      spec:
                        connectorRef: HarnessDocker
                        image: mcr.microsoft.com/playwright:v1.44.0-jammy
                        shell: Sh
                        command: |-
                          apt-get install -y git > /dev/null 2>&1 || true
                          git clone --depth=1 https://github.com/Yashwanth-Tek/internet-banking-concept-microservices.git /app
                          cd /app/tests
                          npm install
                          npx playwright install chromium
                          mkdir -p test-results
                          PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-results/api-contract.xml npx playwright test --config=playwright.config.ts --project=api-contract --reporter=junit
                        envVariables:
                          BASE_URL: http://core-banking-service-svc-stage.banking-dev.svc.cluster.local
                          CI: "true"
                        resources:
                          limits:
                            memory: 1Gi
                            cpu: 500m
                        infrastructure:
                          type: KubernetesDirect
                          spec:
                            connectorRef: hrnslcl
                            namespace: harness-delegate-ng
                            resources:
                              limits:
                                cpu: "1"
                                memory: 1Gi
                            annotations: {}
                            labels: {}
                            containerSecurityContext:
                              capabilities:
                                drop: []
                                add: []
                            nodeSelector: {}
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - /app/tests/test-results/api-contract.xml
                        outputVariables: []
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 5m
                  spec:
                    skipDryRun: false
              - step:
                  type: K8sBlueGreenStageScaleDown
                  name: Blue Scale Down
                  identifier: Blue_Scale_Down
                  spec:
                    deleteResources: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
