apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking-service
  namespace: test-qa
  labels:
    app: core-banking-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: core-banking-service
  template:
    metadata:
      labels:
        app: core-banking-service
    spec:
      containers:
        - name: core-banking-service
          image: yashwanth536/core-banking-service:5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "8092"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 5
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
