apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: core-banking-service-pdb
  namespace: banking-dev
  annotations:
    harness.io/direct-apply: "true"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: core-banking-service
