---
apiVersion: v1
kind: Service
metadata:
  name: core-banking-service-svc
  namespace: test-qa
  annotations:
    harness.io/primary-service: "true"
  labels:
    app: core-banking-service
spec:
  type: ClusterIP
  selector:
    app: core-banking-service
  ports:
    - name: http
      port: 80
      targetPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: core-banking-service-svc-stage
  namespace: test-qa
  annotations:
    harness.io/stage-service: "true"
  labels:
    app: core-banking-service
spec:
  type: ClusterIP
  selector:
    app: core-banking-service
  ports:
    - name: http
      port: 80
      targetPort: 8092
