apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: banking-dev
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: yashwanth536/user-service:7
          ports:
            - containerPort: 8083

          env:
            - name: SERVER_PORT
              value: "8083"

            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"

            - name: EUREKA_CLIENT_ENABLED
              value: "false"

            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-javatodev-app:3306/banking_user_service"

            - name: SPRING_DATASOURCE_USERNAME
              value: "javatodev_development"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "oPItyPticIAt"

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            periodSeconds: 15
