apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: test-qa
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc-stage
  namespace: test-qa
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
      protocol: TCP
