apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-payment-service
  namespace: banking-dev
  labels:
    app: utility-payment-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: utility-payment-service
  template:
    metadata:
      labels:
        app: utility-payment-service
    spec:
      containers:
        - name: utility-payment-service
          image: yashwanth536/utility-payment-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 8
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 8
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
